/**
 * scripts/downloadCairoFont.mjs
 * Downloads Cairo Regular TTF from Google Fonts and saves it as a
 * Base64 JS module so jsPDF can embed it for proper Arabic rendering.
 *
 * Run once:  node scripts/downloadCairoFont.mjs
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname }           from 'path';
import { fileURLToPath }           from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));

// Google Fonts static CDN — Cairo Regular (v28, subset: Arabic + Latin)
// Regenerate URL: node -e "fetch('https://fonts.googleapis.com/css2?family=Cairo:wght@400',{headers:{'User-Agent':'Mozilla/5.0'}}).then(r=>r.text()).then(t=>console.log([...t.matchAll(/src: url\(([^)]+\.ttf)\)/g)].map(m=>m[1]).join('\n')))"
const FONT_URLS = [
  'https://fonts.gstatic.com/s/cairo/v31/SLXgc1nY6HkvangtZmpQdkhzfH5lkSs2SgRjCAGMQ1z0hOA-W1Q.ttf',
  'https://fonts.gstatic.com/s/cairo/v28/SLXgc1nY6HkvalIvTp2mxdtUXA.ttf',
];

async function download(url) {
  const res = await fetch(url, {
    headers: { 'User-Agent': 'Mozilla/5.0 (compatible; MoraqebWeb/1.0)' },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return Buffer.from(await res.arrayBuffer());
}

let buf = null;
for (const url of FONT_URLS) {
  try {
    console.log(`Trying: ${url}`);
    buf = await download(url);
    console.log(`  Downloaded ${(buf.length / 1024).toFixed(0)} KB`);
    break;
  } catch (e) {
    console.warn(`  Failed: ${e.message}`);
  }
}

if (!buf) {
  console.error('All font URLs failed. Check your internet connection.');
  process.exit(1);
}

const base64 = buf.toString('base64');
const outDir  = join(__dir, '../src/assets/fonts');
const outFile = join(outDir, 'CairoFont.js');

mkdirSync(outDir, { recursive: true });

writeFileSync(outFile, [
  '// Cairo Regular — TTF as Base64',
  '// Generated by: node scripts/downloadCairoFont.mjs',
  '// DO NOT edit manually.',
  `// Size: ${(base64.length / 1024).toFixed(0)} KB (base64)`,
  '',
  `export const cairoBase64 = "${base64}";`,
  '',
].join('\n'), 'utf8');

console.log(`\n✅  Saved → ${outFile}`);
console.log(`   Base64 length: ${base64.length.toLocaleString()} chars`);
