/**
 * scripts/downloadCairoFont.mjs
 * Downloads Cairo Regular and Bold from Google Fonts and saves them as a
 * Base64 JS module so jsPDF can embed them for proper Arabic rendering.
 *
 * Both weights matter: jsPDF cannot synthesise bold. Asking for a bold style
 * that was never registered makes it fall back to a built-in Latin font, which
 * renders Arabic as blank boxes — so a report with bold headings would lose its
 * headings entirely.
 *
 * Run:  node scripts/downloadCairoFont.mjs
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname }           from 'path';
import { fileURLToPath }           from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));

/* Resolved from the CSS API rather than hard-coded, so a version bump on
   Google's side does not silently 404 the build. */
async function resolveTtf(weight) {
  const css = await fetch(
    `https://fonts.googleapis.com/css2?family=Cairo:wght@${weight}`,
    { headers: { 'User-Agent': 'Mozilla/5.0 (compatible; AwjHub/1.0)' } },
  ).then(r => r.text());

  const urls = [...css.matchAll(/src:\s*url\(([^)]+\.ttf)\)/g)].map(m => m[1]);
  if (!urls.length) throw new Error(`no TTF in CSS for weight ${weight}`);
  return urls;
}

async function download(url) {
  const res = await fetch(url, {
    headers: { 'User-Agent': 'Mozilla/5.0 (compatible; AwjHub/1.0)' },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

async function fetchWeight(weight, label) {
  const urls = await resolveTtf(weight);
  for (const url of urls) {
    try {
      console.log(`${label}: ${url}`);
      const buf = await download(url);
      console.log(`  ✅  ${(buf.length / 1024).toFixed(0)} KB`);
      return buf.toString('base64');
    } catch (e) {
      console.warn(`  ✗  ${e.message}`);
    }
  }
  throw new Error(`could not download ${label}`);
}

const regular = await fetchWeight(400, 'Cairo Regular');
const bold    = await fetchWeight(700, 'Cairo Bold');

const outDir  = join(__dir, '../src/assets/fonts');
const outFile = join(outDir, 'CairoFont.js');
mkdirSync(outDir, { recursive: true });

writeFileSync(outFile, [
  '// Cairo Regular + Bold — TTF as Base64',
  '// Generated by: node scripts/downloadCairoFont.mjs',
  '// DO NOT edit manually.',
  `// Regular: ${(regular.length / 1024).toFixed(0)} KB · Bold: ${(bold.length / 1024).toFixed(0)} KB (base64)`,
  '',
  `export const cairoBase64 = "${regular}";`,
  '',
  `export const cairoBoldBase64 = "${bold}";`,
  '',
].join('\n'), 'utf8');

console.log(`\n✅  Saved → ${outFile}`);
