-- 018_fridge_receipts.sql
--
-- إقرار استلام ثلاجات, for منى and for عرفة.
--
-- The company's own handover receipt, so it goes out on our letterhead and its
-- ruled blocks use the neutral palette — a form issued by us must not arrive
-- looking like the ministry's green sheet.
--
-- Centre-scoped: the shakhis and the centre number are the point of the
-- receipt, so the assignment screen will only issue it per centre.
--
--   the system   shakhis, centre number, caterer, the owner's name, the date
--   the office   how many fridges, its own representative, and that signature
--   the caterer  one signature, and nothing else
--
-- Generated from src/config/standardForms.js, which stays the source of truth.
-- Regenerate rather than editing the JSON below by hand.

INSERT INTO public.form_templates
  (key, title, description, category, definition,
   requires_signature, requires_attachment, is_standard, active, updated_at)
VALUES
  ('fridge_receipt_mina', 'إقرار استلام ثلاجات (منى)', 'إقرار المتعهد باستلام ثلاجات المركز بمشعر منى سليمةً وعاملة، بعد المعاينة والفحص.', 'تشغيلي',
   '{"scope":"center","blocks":[{"id":"head","type":"grid","palette":"plain","widths":["17%","33%","17%","33%"],"rows":[{"cells":[{"text":"رقم الشاخص","tone":"label"},{"field":"shakhis"},{"text":"رقم المركز","tone":"label"},{"field":"center_code"}]},{"cells":[{"text":"الموقع","tone":"label"},{"text":"منى","align":"center"},{"text":"التاريخ","tone":"label"},{"field":"receipt_date"}]},{"cells":[{"text":"اسم المتعهد","tone":"label"},{"field":"caterer_name","span":3}]}]},{"id":"h1","type":"heading","text":"تفاصيل الإقرار"},{"id":"p1","type":"paragraph","text":"نفيدكم بأنه تم تسليم واستلام الثلاجات المخصصة للمركز المذكور أعلاه من قبل المتعهد، وذلك بحضور كل من (ممثل لجنة التغذية، ممثل متعهد الإعاشة و ممثل لجنة المشاعر). ونؤكد أنه تم تسليمها وفق الموعد وآلية التسليم المحددة، وبعد إجراء المعاينة والفحص اللازمين للعهد، نقر بما يلي:"},{"id":"l1","type":"list","ordered":false,"items":["عدد الثلاجات المستلمة: ({{fridge_count}}) ثلاجة.","حالة الثلاجات: الثلاجات سليمة وتعمل بحالة جيدة.","حالة الهيكل: الهيكل الخارجي والداخلي سليم وخالٍ من الكسور أو الانبعاجات.","المفاتيح: تم تسليم نسخة واحدة من المفاتيح."]},{"id":"p2","type":"paragraph","text":"وهذا إقرار منا بالاستلام وبسلامة العهدة المذكورة أعلاه."},{"id":"f1","type":"fields","style":"list","keys":["notes"]},{"id":"h2","type":"heading","text":"التوقيعات والاعتماد"},{"id":"sign","type":"grid","palette":"plain","widths":["12%","38%","12%","38%"],"rows":[{"cells":[{"text":"ممثل لجنة التغذية","tone":"label","accent":true,"span":2,"align":"center"},{"text":"ممثل متعهد الإعاشة","tone":"label","accent":true,"span":2,"align":"center"}]},{"cells":[{"text":"الاسم","tone":"label"},{"field":"committee_rep_name"},{"text":"الاسم","tone":"label"},{"field":"caterer_rep_name"}]},{"cells":[{"text":"التوقيع","tone":"label"},{"sig":["committee_signature"],"owner":"admin"},{"text":"التوقيع","tone":"label"},{"sig":["caterer_signature"],"owner":"caterer"}]}]}],"fields":{"shakhis":{"label":"رقم الشاخص","type":"text","source":"center.shakhis_mina","readonly":true},"center_code":{"label":"رقم المركز","type":"text","source":"center.code","readonly":true},"caterer_name":{"label":"اسم المتعهد","type":"text","source":"caterer.name","readonly":true},"receipt_date":{"label":"التاريخ","type":"date","source":"today","calendar":"gregorian-long","readonly":true},"fridge_count":{"label":"عدد الثلاجات المستلمة","type":"number","owner":"admin","required":true,"group":"تفاصيل التسليم"},"notes":{"label":"ملاحظات","type":"textarea","owner":"admin","group":"تفاصيل التسليم"},"committee_rep_name":{"label":"الاسم","type":"text","owner":"admin","required":true,"group":"التوقيعات · ممثل لجنة التغذية"},"committee_signature":{"label":"التوقيع","type":"file","owner":"admin","group":"التوقيعات · ممثل لجنة التغذية"},"caterer_rep_name":{"label":"الاسم","type":"text","source":"caterer.owner_name","readonly":true},"caterer_signature":{"label":"التوقيع","type":"file","owner":"caterer","required":true}}}'::jsonb, true, false, true, true, now()),
  ('fridge_receipt_arafat', 'إقرار استلام ثلاجات (عرفة)', 'إقرار المتعهد باستلام ثلاجات المركز بمشعر عرفة سليمةً وعاملة، بعد المعاينة والفحص.', 'تشغيلي',
   '{"scope":"center","blocks":[{"id":"head","type":"grid","palette":"plain","widths":["17%","33%","17%","33%"],"rows":[{"cells":[{"text":"رقم الشاخص","tone":"label"},{"field":"shakhis"},{"text":"رقم المركز","tone":"label"},{"field":"center_code"}]},{"cells":[{"text":"الموقع","tone":"label"},{"text":"عرفة","align":"center"},{"text":"التاريخ","tone":"label"},{"field":"receipt_date"}]},{"cells":[{"text":"اسم المتعهد","tone":"label"},{"field":"caterer_name","span":3}]}]},{"id":"h1","type":"heading","text":"تفاصيل الإقرار"},{"id":"p1","type":"paragraph","text":"نفيدكم بأنه تم تسليم واستلام الثلاجات المخصصة للمركز المذكور أعلاه من قبل المتعهد، وذلك بحضور كل من (ممثل لجنة التغذية، ممثل متعهد الإعاشة و ممثل لجنة المشاعر). ونؤكد أنه تم تسليمها وفق الموعد وآلية التسليم المحددة، وبعد إجراء المعاينة والفحص اللازمين للعهد، نقر بما يلي:"},{"id":"l1","type":"list","ordered":false,"items":["عدد الثلاجات المستلمة: ({{fridge_count}}) ثلاجة.","حالة الثلاجات: الثلاجات سليمة وتعمل بحالة جيدة.","حالة الهيكل: الهيكل الخارجي والداخلي سليم وخالٍ من الكسور أو الانبعاجات.","المفاتيح: تم تسليم نسخة واحدة من المفاتيح."]},{"id":"p2","type":"paragraph","text":"وهذا إقرار منا بالاستلام وبسلامة العهدة المذكورة أعلاه."},{"id":"f1","type":"fields","style":"list","keys":["notes"]},{"id":"h2","type":"heading","text":"التوقيعات والاعتماد"},{"id":"sign","type":"grid","palette":"plain","widths":["12%","38%","12%","38%"],"rows":[{"cells":[{"text":"ممثل لجنة التغذية","tone":"label","accent":true,"span":2,"align":"center"},{"text":"ممثل متعهد الإعاشة","tone":"label","accent":true,"span":2,"align":"center"}]},{"cells":[{"text":"الاسم","tone":"label"},{"field":"committee_rep_name"},{"text":"الاسم","tone":"label"},{"field":"caterer_rep_name"}]},{"cells":[{"text":"التوقيع","tone":"label"},{"sig":["committee_signature"],"owner":"admin"},{"text":"التوقيع","tone":"label"},{"sig":["caterer_signature"],"owner":"caterer"}]}]}],"fields":{"shakhis":{"label":"رقم الشاخص","type":"text","source":"center.shakhis_arafat","readonly":true},"center_code":{"label":"رقم المركز","type":"text","source":"center.code","readonly":true},"caterer_name":{"label":"اسم المتعهد","type":"text","source":"caterer.name","readonly":true},"receipt_date":{"label":"التاريخ","type":"date","source":"today","calendar":"gregorian-long","readonly":true},"fridge_count":{"label":"عدد الثلاجات المستلمة","type":"number","owner":"admin","required":true,"group":"تفاصيل التسليم"},"notes":{"label":"ملاحظات","type":"textarea","owner":"admin","group":"تفاصيل التسليم"},"committee_rep_name":{"label":"الاسم","type":"text","owner":"admin","required":true,"group":"التوقيعات · ممثل لجنة التغذية"},"committee_signature":{"label":"التوقيع","type":"file","owner":"admin","group":"التوقيعات · ممثل لجنة التغذية"},"caterer_rep_name":{"label":"الاسم","type":"text","source":"caterer.owner_name","readonly":true},"caterer_signature":{"label":"التوقيع","type":"file","owner":"caterer","required":true}}}'::jsonb, true, false, true, true, now())
ON CONFLICT (key) DO UPDATE SET
  title               = EXCLUDED.title,
  description         = EXCLUDED.description,
  category            = EXCLUDED.category,
  definition          = EXCLUDED.definition,
  requires_signature  = EXCLUDED.requires_signature,
  requires_attachment = EXCLUDED.requires_attachment,
  is_standard         = true,
  active              = true,
  updated_at          = now();
